# Generated by Django 4.1.5 on 2023-02-06 18:35

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=places.models.get_uploading_path, verbose_name='Файл'),
        ),
    ]
