# Generated by Django 4.1.5 on 2023-01-15 06:07

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
